### PR TITLE
Add guide to use Qt Creator as IDE

### PR DESCRIPTION
**Pull request by salkinium**
@rleh has created this really cool guide on how to use Qt Creator as an IDE.

I got this working on OS X, but ran into the following issues:
- The precompiled, official `arm-none-eabi-gdb` does not support Python scripting, [instead `arm-none-eabi-gdb-py` has to be chosen as the debugger](https://bugs.launchpad.net/gcc-arm-embedded/+bug/1294231) and it is only available since the 4.9 2015q4 release.
- I have a custom `PATH`, which needs to be manually added to the Kit settings.

Furthermore, I would like to use our [`getting-started-with-xpcc`](https://github.com/roboterclubaachen/getting-started-with-xpcc) repo as an example.

cc @ekiwi @rleh 

PS: xpcc vs. XPCC: the first one is the framework, the second one is the protocol. Yes, I know, confusing.

### CODE REVIEW

**Comment by rleh** [comment]
> The precompiled, official arm-none-eabi-gdb does not support Python scripting, instead arm-none-eabi-gdb-py has to be chosen as the debugger and it is only available since the 4.9 2015q4 release.

Ok, on my Fedora 22 and 23 the `arm-none-eabi-gdb` packages have python support enabled.
What about python support in `arm-none-eabi-gdb` on Ubuntu or Arch?

> I have a custom PATH, which needs to be manually added to the Kit settings.

Hmmm, where is `PATH` used?

> Furthermore, I would like to use our getting-started-with-xpcc repo as an example.

I did not know a `getting-started-with-xpcc` repo exists, but I can adapt the guide. (And fix _xpcc_/_XPCC_ :grinning: )

**Comment by ekiwi** [comment]
ping?

**Comment by salkinium** [comment]
[Here is a docs link with my edits and comments](https://docs.google.com/document/d/1mliIYuYLhp8E_Xir7j7FXrxp84w5B3GDXlkPCY-DLuk/edit?usp=sharing).

**Comment by daniel-k** [comment]
@rleh @salkinium ping

**Comment by salkinium** [comment]
Sorry, I dropped the ball on this.
I'll work on it this week.

**Comment by salkinium** [comment]
I reworked this to use the `getting-started-with-xpcc` repository, since that is a "neutral" project that people can actually access.

**Pull request merged**
